version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - example.env
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/myportfolio
    depends_on:
      - mySql

  mySql:
    container_name: mySql
    image: mardiadb
    restart: always
    env_file:
      - example.env
    volumes:
      - mydatabase:/var/lib/mySql

volumes:
  mydatabase: