version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - example.env
    ports:
      - "5000:5000"
    depends_on:
      - mySql

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment: [reggie@testing.com]
    ports:
    - 80:80
    - 443:443
    volumes:
    - nginx_secrets:/etc/letsenscrypt
    - ./user.conf.d:/etc/nginx/user_conf.d
    depends_on:
    - myportfolio



  mySql:
    container_name: mySql
    image: mariadb
    restart: always
    env_file:
      - example.env
    volumes:
      - mydatabase:/var/lib/mySql
    command:
      ["--wait-timeout=10000", "--max-allowed-packet=256M"]

volumes:
  mydatabase:
  nginx_secrets:
